name: upload-artifacts-and-release
on: [push]
jobs:
  checkout-latest-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: python setup.py sdist
      - uses: actions/upload-artifact@v3
        with:
          name: terraform_source_code
          path: terraform_resources/
      - uses: actions/upload-artifact@v3
        with:
          name: py_lambda_warmer.zip
          path: dist/py_lambda_warmer*.gz
