name: upload-artifacts-and-release
on:
  push:
    branches:
      - "master"
jobs:
  checkout-latest-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: python setup.py sdist
      - run: echo "RELEASE=$(cat release)"
      - run: echo $RELEASE
