name: testing-python-code
on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - "feature/**"
jobs:
  test-code:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: pip install tox
      - run: tox
      